# Generated by Django 3.0.7 on 2020-08-17 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AREAPROFESIONAL',
            fields=[
                ('nombre_area', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PROCEDIMIENTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procedimiento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RECURSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_recurso', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PROFESIONAL',
            fields=[
                ('identificador_medico', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=150)),
                ('apellidos', models.CharField(default='', max_length=150)),
                ('tipo_profesional', models.CharField(choices=[('MIR', 'MIR'), ('CIRUJANO', 'CIRUJANO')], default='', max_length=150)),
                ('edad', models.IntegerField()),
                ('area_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processmining.AREAPROFESIONAL')),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTE',
            fields=[
                ('identificador_medico', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('sexo_paciente', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='', max_length=150)),
                ('origen_paciente', models.CharField(choices=[('URBANA', 'URBANA'), ('RURAL', 'RURAL')], default='', max_length=150)),
                ('edad', models.IntegerField()),
                ('fecha_inclusion', models.DateField(default=django.utils.timezone.now)),
                ('diagnostico', models.CharField(max_length=150)),
                ('procedimiento_paciente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='processmining.PROCEDIMIENTOS', verbose_name='tipo de procedimiento asociado a un paciente')),
                ('profesional_paciente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='processmining.PROFESIONAL', verbose_name='Profesional asociado a un paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ACTIVIDAD_PACIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('horaInicio', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('minutoInicio', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('DuracionMinutos', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('id_actividad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='processmining.ACTIVIDAD', verbose_name='Identificador de la actividad asociada')),
                ('id_paciente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='processmining.PACIENTE', verbose_name='Identificador del paciente al que se le aplica')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='recurso_asociado',
            field=models.ManyToManyField(to='processmining.RECURSO', verbose_name='tipo de recuerso profesional asociado a una actividad'),
        ),
    ]
