# Generated by Django 3.0.7 on 2020-08-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processmining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='area_prof',
        ),
    ]
