# Generated by Django 3.0.7 on 2020-08-17 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processmining', '0003_auto_20200817_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad_paciente',
            name='DuracionMinutos',
        ),
        migrations.RemoveField(
            model_name='actividad_paciente',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='actividad_paciente',
            name='horaInicio',
        ),
        migrations.RemoveField(
            model_name='actividad_paciente',
            name='minutoInicio',
        ),
        migrations.AddField(
            model_name='actividad_paciente',
            name='duracion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
